#!binbash

# Function to get CPU information
get_cpu_info() {
    CPU=$(lshw -class processor  awk 'product {gsub(product, ); print}')
    CPU_SPEED=$(lscpu  awk '^CPU MHz {print $3}')
    MAX_SPEED=$(lscpu  awk '^CPU max MHz {print $4}')
    echo cpu $CPU
    echo Speed $CPU_SPEED MHz (Max $MAX_SPEED MHz)
}

# Function to get RAM information
get_ram_info() {
    RAM=$(free -h  awk '^Mem {print $2}')
    echo Ram $RAM
}

# Function to get disk information
get_disk_info() {
    df -h  awk 'NR==1 {next} {print Disk(s), $1, $2}'
}

# Function to get video card information (assuming there's a single video card)
get_video_info() {
    VIDEO=$(lspci  grep VGA  awk -F  '{print $2}')
    echo Video $VIDEO
}

# Function to get network information
get_network_info() {
    FQDN=$(hostname --fqdn)
    HOST_IP=$(hostname -I  awk '{print $1}')
    GATEWAY=$(ip r  awk 'default via {print $3}')
    DNS=$(grep nameserver etcresolv.conf  awk '{print $2}')
    
    echo FQDN $FQDN
    echo Host Address $HOST_IP
    echo Gateway IP $GATEWAY
    echo DNS Server $DNS
    
    # Assuming we're interested in the primary network interface
    INTERFACE=$(ip -o -4 route show to default  awk '{print $5}')
    IP_ADDRESS=$(ip a show dev $INTERFACE  awk 'inet  {print $2}')
    echo $INTERFACE $IP_ADDRESS
}

# Function to get system status information
get_system_status() {
    USERS=$(who  awk '{print $1}'  sort -u  tr 'n' ',')
    DISK_SPACE=$(df -h  awk 'NR==1 {next} {print $4  free on  $6}')
    PROCESS_COUNT=$(ps aux  wc -l)
    LOAD_AVG=$(cat procloadavg  awk '{print $1 ,  $2 ,  $3}')
    MEMORY=$(free -h  awk 'Mem {print Total  $2 , Used  $3 , Free  $4}')
    NETWORK_PORTS=$(ss -tuln  awk 'NR  1 {print $5}'  cut -d'' -f2  sort -u  tr 'n' ',')
    UFW_RULES=$(sudo ufw status numbered)
    
    echo Users Logged In ${USERS-1}  # Remove trailing comma
    echo Disk Space $DISK_SPACE
    echo Process Count $PROCESS_COUNT
    echo Load Averages $LOAD_AVG
    echo Memory Allocation $MEMORY
    echo Listening Network Ports ${NETWORK_PORTS-1}  # Remove trailing comma
    echo UFW Rules
    echo $UFW_RULES
}

# Main script execution starts here
clear  # Clear the screen for cleaner output
echo System Report generated by $USER, $(date)
echo

echo System Information
echo ------------------
hostnamectl  grep 'Static hostname'
source etcos-release
echo Uptime $(uptime -p)
echo

echo Hardware Information
echo --------------------
get_cpu_info
get_ram_info
get_disk_info
get_video_info
echo

echo Network Information
echo -------------------
get_network_info
echo

echo System Status
echo -------------
get_system_status

